{
  "name": "retry-on-catch",
  "version": "1.0.0",
  "description": "Retry a function when it's caught by try/catch",
  "main": "index.js",
  "scripts": {
    "lint": "eslint src/*.js",
    "prepush": "npm run lint",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/weltonsanches/retry-on-catch.git"
  },
  "keywords": [
    "retry",
    "catch",
    "try-again"
  ],
  "author": "Welton Sanches",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/weltonsanches/retry-on-catch/issues"
  },
  "homepage": "https://github.com/weltonsanches/retry-on-catch#readme",
  "devDependencies": {
    "eslint": "^7.27.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.23.3",
    "husky": "^6.0.0"
  }
}
